title: Applications of Data Science
logo: /assets/img/logo.gif
description: Friday July 28, 2023 (1:00 - 4:00 pm PT), Friday August 4, 2023 (1:00 - 4:00 pm PT)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
